import { Header } from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeContextProvider } from "@/contexts/themeContext";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <ThemeContextProvider>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </ThemeContextProvider>
      </QueryClientProvider>
    </html>
  );
}
